### ISSUE TITLE
Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by Wrench333** [kishan-dhankecha/carousel_slider_plus#5]
While using the nextPage() and previousPage() function of the CarouselSliderController it returns a Null check operator used on null value error. I was facing the same issue on carousel_slider package and after looking online switched to the carousel_slider_plus package to face the same issue. I was using hooks initially but currently I removed even that just in case that was the reason but it didn't help with the issue. Can anyone please help me with this ?

The code I am using is as below: 
```
import 'package:carousel_slider_plus/carousel_slider_plus.dart';
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

import '../../business_logic_components/matches_providers.dart';

class DateSliderCarousel extends ConsumerStatefulWidget {
  DateSliderCarousel({
    super.key,
    this.isNextPossible = true,
    this.isPrevPossible = true,
    this.dates = const [17, 18, 19, 20, 21, 22, 23],
    this.today = 20,
  });
  bool isNextPossible;
  bool isPrevPossible;
  List<int> dates;
  int today;

  @override
  ConsumerState<DateSliderCarousel> createState() => _DateSliderCarouselState();
}

class _DateSliderCarouselState extends ConsumerState<DateSliderCarousel> {
  @override
  Widget build(BuildContext context) {
    var currentDate = ref.watch(dateProvider);
    var selectedIndex = currentDate.day - 17;
    final CarouselSliderController _controller = CarouselSliderController();
    return Stack(
      alignment: Alignment.center,
      children: [
        SizedBox(
          child: CarouselSlider(
            controller: _controller,
            options: CarouselOptions(
              onPageChanged: (index, reason) {
                selectedIndex = index;
                ref.read(dateProvider.notifier).state =
                    DateTime(2024, 9, widget.dates[index]);
              },
              aspectRatio: 7,
              viewportFraction: 0.3,
              enlargeFactor: 0.3,
              scrollDirection: Axis.horizontal,
              enlargeCenterPage: true,
              initialPage: selectedIndex, //DateTime.now().day - 17
              enableInfiniteScroll: false,
              animateToClosest: true,
              pageSnapping: true,
              autoPlay: false,
              pauseAutoPlayOnManualNavigate: true,
              pauseAutoPlayInFiniteScroll: true,
              pauseAutoPlayOnTouch: true,
            ),
            items: List.generate(
              widget.dates.length,
              (index) {
                return (index == selectedIndex)
                    ? Container(
                        decoration: ShapeDecoration(
                          gradient: LinearGradient(
                            begin: Alignment.topLeft,
                            end: Alignment.bottomRight,
                            colors: [Color(0xFF13544C), Color(0xFF090C01)],
                          ),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(16),
                          ),
                        ),
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            // (currentDate.day == 18) //DateTime.now().day
                            //     ? Text(
                            //         'Today',
                            //         style: TextStyle(
                            //           color: Colors.white,
                            //           fontSize: 14,
                            //           fontFamily: 'Source Sans Pro',
                            //           fontWeight: FontWeight.w600,
                            //           height: 0,
                            //         ),
                            //       )
                            //     : SizedBox(),
                            Container(
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Text(
                                    '${widget.dates[index]}th Sept',
                                    style: TextStyle(
                                      color: Color(0xFF3DF2BB),
                                      fontSize: 16,
                                      fontFamily: 'Source Sans Pro',
                                      fontWeight: FontWeight.w600,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      )
                    : Container(
                        margin: EdgeInsets.symmetric(horizontal: 0.05.sw),
                        decoration: ShapeDecoration(
                          color: Color(0xFF090C01),
                          shape: RoundedRectangleBorder(
                            side:
                                BorderSide(width: 1, color: Color(0xFF13544C)),
                            borderRadius: BorderRadius.circular(14),
                          ),
                        ),
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Text(
                              '${widget.dates[index]}',
                              style: TextStyle(
                                color: Color(0xFF8B8B8B),
                                fontSize: 16,
                                fontFamily: 'Source Sans Pro',
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                          ],
                        ),
                      );
              },
            ),
          ),
        ),
        Positioned(
          left: 0.1.sw,
          child: InkWell(
            onTap: widget.isPrevPossible && selectedIndex > 0
                ? () {
                    _controller.previousPage(
                      duration: const Duration(milliseconds: 300),
                      curve: Curves.easeIn,
                    );
                    (selectedIndex == 0)
                        ? widget.isPrevPossible = false
                        : widget.isPrevPossible = true;
                    (selectedIndex == 6)
                        ? widget.isNextPossible = false
                        : widget.isNextPossible = true;
                    // controller.previousPage(
                    //   duration: const Duration(milliseconds: 300),
                    //   curve: Curves.easeIn,
                    // );
                  }
                : null,
            child: Container(
              width: 0.2.sw,
              height: 1.sw / 7,
            ),
          ),
        ),
        Positioned(
          right: 0.1.sw,
          child: InkWell(
            onTap:
                widget.isNextPossible && selectedIndex < widget.dates.length - 1
                    ? () {
                        _controller.nextPage(
                          duration: const Duration(milliseconds: 300),
                          curve: Curves.ease,
                        );
                        (selectedIndex == 0)
                            ? widget.isPrevPossible = false
                            : widget.isPrevPossible = true;
                        (selectedIndex == 6)
                            ? widget.isNextPossible = false
                            : widget.isNextPossible = true;
                      }
                    : null,
            child: Container(
              width: 0.2.sw,
              height: 1.sw / 7,
            ),
          ),
        ),
      ],
    );
  }
}
```

The Error is as below: 
`/flutter (19442): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (19442): #0      CarouselSliderController.nextPage (package:carousel_slider_plus/carousel_controller.dart:32:41)
E/flutter (19442): #1      _DateSliderCarouselState.build.<anonymous closure> (package:bosm_24_app/features/matches/presentation/date_slider/date_slider_carousel.dart:172:37)
E/flutter (19442): #2      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1170:21)
E/flutter (19442): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351:24)
E/flutter (19442): #4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:656:11)
E/flutter (19442): #5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:313:5)
E/flutter (19442): #6      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:246:7)
E/flutter (19442): #7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:703:9)
E/flutter (19442): #8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
E/flutter (19442): #9      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter`

**Comment by Gonn01** [comment]
same error

**Comment by Gonn01** [comment]
> same error

i was not passing the controller to the carousel xd.
 my bad

**Comment by Wrench333** [comment]
> > same error
> 
> i was not passing the controller to the carousel xd. my bad

I am passing the controller to the carousel tho ;-; ?? How did it work for you in the end ? Would be helpful if you could share your code with me :)

**Comment by Gonn01** [comment]
> > > same error
> > 
> > 
> > i was not passing the controller to the carousel xd. my bad
> 
> I am passing the controller to the carousel tho ;-; ?? How did it work for you in the end ? Would be helpful if you could share your code with me :)

```dart
class ObservationPicture extends StatefulWidget {
  const ObservationPicture({
    super.key,
  });

  @override
  State<ObservationPicture> createState() => _ObservationPictureState();
}

class _ObservationPictureState extends State<ObservationPicture> {
  final CarouselSliderController _controller = CarouselSliderController();

  int current = 0;
  List<String> images = [
    'https://m.media-amazon.com/images/I/51rayl0HnRL._SY550_.jpg',
    'https://m.media-amazon.com/images/I/51rayl0HnRL._SY550_.jpg',
    'https://m.media-amazon.com/images/I/51rayl0HnRL._SY550_.jpg',
  ];
  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: const BorderRadius.only(
          bottomLeft: Radius.circular(20),
          bottomRight: Radius.circular(20),
        ),
        boxShadow: [
          BoxShadow(
            color: Colors.grey.withOpacity(0.5),
            spreadRadius: 1,
            blurRadius: 1,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        children: [
          Padding(
            padding:
                const EdgeInsets.symmetric(horizontal: 10).copyWith(bottom: 10),
            child: images.isEmpty
                ? Container(
                    decoration: const BoxDecoration(
                      color: Colors.grey,
                      borderRadius: BorderRadius.all(Radius.circular(20)),
                    ),
                    child: const Padding(
                      padding: EdgeInsets.all(25),
                      child: Center(
                        child: Icon(
                          Icons.camera_alt_outlined,
                          size: 150,
                          color: Colors.purple,
                        ),
                      ),
                    ),
                  )
                : Column(
                    children: [
                      CarouselSlider.builder(
                        options: CarouselOptions(
                          initialPage: current,
                          enableInfiniteScroll: false,
                          onPageChanged: (index, _) =>
                              setState(() => current = index),
                        ),
                        itemCount: images.length,
                        itemBuilder: (
                          BuildContext context,
                          int itemIndex,
                          int pageViewIndex,
                        ) {
                          return GestureDetector(
                            onTap: () => showDialog<void>(
                              context: context,
                              builder: (context) => Dialog(
                                child: SizedBox(
                                  child: Image.network(
                                    images[itemIndex],
                                    fit: BoxFit.cover,
                                  ),
                                ),
                              ),
                            ),
                            child: SizedBox(
                              height: 190,
                              child: Image.network(
                                images[itemIndex],
                                fit: BoxFit.cover,
                              ),
                            ),
                          );
                        },
                      ),
                      const SizedBox(height: 10),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: images.asMap().entries.map((entry) {
                          return GestureDetector(
                            onTap: () => _controller.animateToPage(entry.key),
                            child: Container(
                              width: 12,
                              height: 12,
                              margin: const EdgeInsets.symmetric(horizontal: 4),
                              decoration: BoxDecoration(
                                shape: BoxShape.circle,
                                color: (Theme.of(context).brightness ==
                                            Brightness.dark
                                        ? Colors.white
                                        : Colors.black)
                                    .withOpacity(
                                  current == entry.key ? 0.9 : 0.4,
                                ),
                              ),
                            ),
                          );
                        }).toList(),
                      ),
                    ],
                  ),
          ),
        ],
      ),
    );
  }
}
```
This should work, let me know

**Comment by kishan-dhankecha** [comment]
@Wrench333 did you fix your issue?

**Comment by Wrench333** [comment]
> @Wrench333 did you fix your issue?
> 

I'll look into it in a few days. Was busy with my exams ;-;

**Comment by sfx2k** [comment]
The trick is to initialize the CarouselSliderController outside the Build method!

**Comment by kishan-dhankecha** [comment]
I tried with this code and it works as intended.

```dart
import 'package:carousel_slider_plus/carousel_slider_plus.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(
      home: PlayGround(),
    ),
  );
}

class PlayGround extends StatefulWidget {
  const PlayGround({super.key});

  @override
  State<PlayGround> createState() => _PlayGroundState();
}

class _PlayGroundState extends State<PlayGround> {
  final CarouselSliderController _controller = CarouselSliderController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('PlayGround'),
        actions: <Widget>[
          TextButton(
            child: const Text('Test'),
            onPressed: () {
              _controller.animateToPage(2);
            },
          ),
        ],
      ),
      body: CarouselSlider(
        controller: _controller,
        items: List.generate(10, (item) {
          return Container(
            margin: const EdgeInsets.all(5.0),
            color: Colors.cyan,
            child: Center(
              child: Text(item.toString()),
            ),
          );
        }).toList(),
      ),
    );
  }
}
```


As suggested by @sfx2k, Please move your controller initialization out of the build method.

**Comment by tobecwb** [comment]
same for me.

my code:
```
class WelcomePage extends HookWidget {
  ...
  final CarouselSliderController _carouselSliderController = CarouselSliderController();

  WelcomePage({super.key});

  @override
  Widget build(BuildContext context) {
    final selectedOption = useState(SignupRegisterChoiceOptions.signup);

    useValueChanged(selectedOption.value, (_, __) {
      WidgetsBinding.instance.addPostFrameCallback((_) {
        var page =
        selectedOption.value == SignupRegisterChoiceOptions.signup ? 0 : 1;
        _carouselSliderController.animateToPage(page,
            curve: Curves.easeOutQuad);
      });

      return selectedOption.value;
    });

    ...
	
    return LoaderStyle(
      child: Scaffold(
        body: SafeArea(
          child: SingleChildScrollView(
            child: Column(
              children: [
                const Header(),
                const SizedBox(height: espacamento),
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 20.0),
                  child: Column(
                    children: [
                      _buildSignupRegisterChoiceButton(selectedOption),
                      CarouselSlider(
                          options: CarouselOptions(
                            height: 350,
                            viewportFraction: 1,
                            scrollPhysics: const NeverScrollableScrollPhysics(),
                          ),
                          controller: _carouselSliderController,
                          items: [
                            LoginForm(handleLogin: handleLogin),
                            SignupForm(handleRegister: validateUser),
                          ]),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
  
  ...
  
}
```

the error occur on `_carouselSliderController.animateToPage`

The strangest thing is that sometimes it works and sometimes it doesn't. If I restart the Android emulator about 10 times, at least 3 times it will show the error, and other times it will work normally.

I also tried using `useEffect` instead of `useValueChanged` and the result was the same.

**Comment by kishan-dhankecha** [comment]
Try updating the package to the latest version, there have been some changes done related to null safety.
